// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anyproto/any-sync-consensusnode/db (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination mock_db/mock_db.go github.com/anyproto/any-sync-consensusnode/db Service
//

// Package mock_db is a generated GoMock package.
package mock_db

import (
	context "context"
	reflect "reflect"

	consensus "github.com/anyproto/any-sync-consensusnode"
	db "github.com/anyproto/any-sync-consensusnode/db"
	app "github.com/anyproto/any-sync/app"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddLog mocks base method.
func (m *MockService) AddLog(ctx context.Context, log consensus.Log) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLog", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddLog indicates an expected call of AddLog.
func (mr *MockServiceMockRecorder) AddLog(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLog", reflect.TypeOf((*MockService)(nil).AddLog), ctx, log)
}

// AddRecord mocks base method.
func (m *MockService) AddRecord(ctx context.Context, logId string, record consensus.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRecord", ctx, logId, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRecord indicates an expected call of AddRecord.
func (mr *MockServiceMockRecorder) AddRecord(ctx, logId, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRecord", reflect.TypeOf((*MockService)(nil).AddRecord), ctx, logId, record)
}

// Close mocks base method.
func (m *MockService) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockServiceMockRecorder) Close(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockService)(nil).Close), ctx)
}

// DeleteLog mocks base method.
func (m *MockService) DeleteLog(ctx context.Context, logId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLog", ctx, logId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLog indicates an expected call of DeleteLog.
func (mr *MockServiceMockRecorder) DeleteLog(ctx, logId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLog", reflect.TypeOf((*MockService)(nil).DeleteLog), ctx, logId)
}

// FetchLog mocks base method.
func (m *MockService) FetchLog(ctx context.Context, logId, afterRecordId string) (consensus.Log, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchLog", ctx, logId, afterRecordId)
	ret0, _ := ret[0].(consensus.Log)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchLog indicates an expected call of FetchLog.
func (mr *MockServiceMockRecorder) FetchLog(ctx, logId, afterRecordId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchLog", reflect.TypeOf((*MockService)(nil).FetchLog), ctx, logId, afterRecordId)
}

// GetDeletionId mocks base method.
func (m *MockService) GetDeletionId(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeletionId", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeletionId indicates an expected call of GetDeletionId.
func (mr *MockServiceMockRecorder) GetDeletionId(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeletionId", reflect.TypeOf((*MockService)(nil).GetDeletionId), ctx)
}

// Init mocks base method.
func (m *MockService) Init(a *app.App) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockServiceMockRecorder) Init(a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockService)(nil).Init), a)
}

// Name mocks base method.
func (m *MockService) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockServiceMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockService)(nil).Name))
}

// Run mocks base method.
func (m *MockService) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockServiceMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockService)(nil).Run), ctx)
}

// SetChangeReceiver mocks base method.
func (m *MockService) SetChangeReceiver(receiver db.ChangeReceiver) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetChangeReceiver", receiver)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetChangeReceiver indicates an expected call of SetChangeReceiver.
func (mr *MockServiceMockRecorder) SetChangeReceiver(receiver any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetChangeReceiver", reflect.TypeOf((*MockService)(nil).SetChangeReceiver), receiver)
}

// SetDeletionId mocks base method.
func (m *MockService) SetDeletionId(ctx context.Context, lastId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDeletionId", ctx, lastId)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDeletionId indicates an expected call of SetDeletionId.
func (mr *MockServiceMockRecorder) SetDeletionId(ctx, lastId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDeletionId", reflect.TypeOf((*MockService)(nil).SetDeletionId), ctx, lastId)
}
